### ISSUE TITLE
Add a one-click option to hide amounts (like in the mobile wallet)

### ISSUE THREAD

**Issue by dbadol** [BeamMW/beam-ui#1130] opened 2024-05-28 22:48 UTC
**Current situation**
On the desktop wallet, all the amounts (holdings, transaction history, etc.) are always visible and cannot easily be hidden (by instance to make a screenshot, or to avoid prying eyes while waiting for a process to finish, etc.). 

**Solution we propose**
Add an eye-shaped icon on the top right corner (next to the notification icon) to turn on/off the hiding of the values. Similar to what is already done in the mobile wallet, but this time on desktop.

Remark: This icon should also be added to the wallet selection and login window, so that we can activate it before the wallet is open.

**Comment by Maxnflaxl** [comment] 2024-06-15 09:40
Closed, duplicate of https://github.com/BeamMW/beam-ui/issues/1096

**Closed by Maxnflaxl** 2024-06-15 09:40 UTC
