### ISSUE TITLE
DApps: redesign

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#273] opened 2020-11-05 17:38 UTC
We do not 'install' apps, but design includes the 'install' icon. Need to replace with the 'run/launch' icon
![gnome-shell-screenshot-29JVT0](https://user-images.githubusercontent.com/12074933/98276327-dbf17a00-1fa6-11eb-86db-b96b9017ffa9.png)

**Comment by gingervik** [comment] 2021-01-18 08:31
Consider screen redesign

**Comment by dariatarakanova** [comment] 2021-03-02 08:17
duplicate of https://github.com/BeamMW/beam-ui/issues/450

**Closed** 2021-03-02 08:17 UTC
