### ISSUE TITLE
Contracts: transactions list

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#385] opened 2020-11-26 14:37 UTC
At the moment we have incorrect data in transactions table. Need to

1) Add amounts
2) Meaningful comments (via apps comments passthroug)
3) Error message on errors
4) Need add general 'Contract icon'

**Comment by chapati** [comment] 2021-01-14 20:49
2. Done, meaningful comments added 

![Screenshot-20210114234839-706x436](https://user-images.githubusercontent.com/12074933/104647533-1112fa80-56c3-11eb-9f1e-53bef3ef198a.png)

**Comment by dariatarakanova** [comment] 2021-01-18 16:46
duplicate of https://github.com/BeamMW/beam-ui/issues/458

**Closed** 2021-01-19 10:45 UTC
Labels: task
