### ISSUE TITLE
Update splash screen with new logo and graphics

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#779] opened 2021-08-25 18:52 UTC

**Comment by gingervik** [comment] 2021-09-06 11:49
duplicate of https://github.com/BeamMW/beam-ui/issues/17?
@alexandrashelenkova @sasha-abramovich

**Comment by alexandrashelenkova** [comment] 2021-09-06 12:14
Yes, seems it's a duplicate, sorry.

**Closed** 2022-10-03 11:37 UTC
