### ISSUE TITLE
Notifications. Day and time parameters duplicates and include "HH.MM" and "dd.mm.yyyy"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#351] opened 2020-11-25 14:13 UTC
Currently in wallet displays "HH.MM" and "dd.mm.yyyy" near the data and time

![image](https://user-images.githubusercontent.com/47353570/101158097-da61b300-3633-11eb-9fd2-73af4033e5b6.png)

Correct view https://zpl.io/awXx1Eg

![image](https://user-images.githubusercontent.com/47353570/101158066-ca49d380-3633-11eb-9d58-ce2e6506ebd3.png)

**Comment by gingervik** [comment] 2020-12-07 06:39
Duplicate of #323

**Closed** 2020-12-07 11:55 UTC
Labels: Product, beamX, bug
