### ISSUE TITLE
Settings: complete verification

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#56] opened 2020-06-08 10:48 UTC
Need to check if we need this option int the GUI wallet.
![DeepinScreenshot_select-area_20200608134828](https://user-images.githubusercontent.com/12074933/84022336-be37ce80-a98e-11ea-933a-b3978a86f800.png)

**Comment by Roberrtt** [comment] 2020-06-24 08:16
Please align the switches.
![Screenshot_18](https://user-images.githubusercontent.com/50007056/85520816-17993200-b60c-11ea-9b78-bffd914a07b5.png)

**Comment by dariatarakanova** [comment] 2021-08-06 09:33
duplicate of https://github.com/BeamMW/beam-ui/issues/756

**Closed by dariatarakanova** 2021-08-06 09:33 UTC
