### ISSUE TITLE
When switching applications, the previous application is displayed

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#446] opened 2021-01-11 13:03 UTC
When we switch to another application, the previous application is displayed
![bandicam-2021-01-11-15-54-11-743](https://user-images.githubusercontent.com/50007056/104185778-801ff300-5426-11eb-845f-cde410db3bea.gif)

**Comment by chapati** [comment] 2021-01-13 09:37
Duplicate of #283

**Closed by chapati** 2021-01-13 09:37 UTC
Labels: beamX, bug
