### ISSUE TITLE
Сontracts: notifications

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#296] opened 2020-11-18 14:07 UTC
Notifications are disabled for contract transactions. Need to discuss & implement

**Comment by chapati** [comment] 2021-01-15 22:55
Need to add 'Contract transaction completed & failed' icons

**Comment by dariatarakanova** [comment] 2021-01-18 16:37
duplicate of https://github.com/BeamMW/beam-ui/issues/457

**Closed** 2021-01-19 10:45 UTC
Labels: task
