### ISSUE TITLE
Move QR code from 'Receive' dialog to either a separate dialog or 'Show address' dialog'

### ISSUE THREAD

**Issue by beam-mw** [BeamMW/beam-ui#206] opened 2020-09-23 10:01 UTC
Currently the QR code appears directly in the Receive dialog and it takes a lot of space now that we have more addresses to show. Especially as in 5.2 we will _probably_ change the selector from 'Regular / Offline' to 'Regular / Max Privacy' and move the offline token to the same screen as two online ones.

**Comment by dariatarakanova** [comment] 2020-10-08 15:16
duplicate of https://github.com/BeamMW/beam-ui/issues/217

**Closed** 2020-10-08 15:17 UTC
